export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL || '';
export const CLIENT_NAME = process.env.NEXT_PUBLIC_CLIENT_NAME;
export const SYSTEM_REFETCH_TIMEOUT_MS =
  process.env.NEXT_PUBLIC_SYSTEM_REFETCH_TIMEOUT_MS;
export const NUMBER_OF_WHATSAPP_RECIPIENT =
  process.env.NEXT_PUBLIC_NUMBER_OF_WHATSAPP_RECIPIENT;
